# Generated by Django 2.2.12 on 2020-04-06 12:43

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=2000)),
            ],
            options={
                'ordering': ('name', 'type'),
            },
        ),
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="A unique code, eg 'ons' or 'unit_id'", max_length=500, unique=True)),
                ('description', models.CharField(blank=True, help_text="The name of the code, eg 'Office of National Statitics' or 'Ordnance Survey ID'", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
            },
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(help_text="Describe this generation, eg '2010 electoral boundaries'", max_length=255)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='NameType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="A unique code to identify this type of name: eg 'english' or 'iso'", max_length=500, unique=True)),
                ('description', models.CharField(blank=True, help_text="The name of this type of name, eg 'English' or 'ISO Standard'", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text="A unique code, eg 'CTR', 'CON', etc", max_length=500, unique=True)),
                ('description', models.CharField(blank=True, help_text="The name of the type of area, eg 'Country', 'Constituency', etc", max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Postcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postcode', models.CharField(db_index=True, max_length=7, unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('areas', models.ManyToManyField(blank=True, related_name='postcodes', to='mapit.Area')),
            ],
            options={
                'ordering': ('postcode',),
            },
        ),
        migrations.CreateModel(
            name='Geometry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polygon', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polygons', to='mapit.Area')),
            ],
            options={
                'verbose_name_plural': 'geometries',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='areas_m2m', to='mapit.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='areas_direct', to='mapit.Country'),
        ),
        migrations.AddField(
            model_name='area',
            name='generation_high',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='final_areas', to='mapit.Generation'),
        ),
        migrations.AddField(
            model_name='area',
            name='generation_low',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_areas', to='mapit.Generation'),
        ),
        migrations.AddField(
            model_name='area',
            name='parent_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='mapit.Area'),
        ),
        migrations.AddField(
            model_name='area',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='mapit.Type'),
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='mapit.Area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='mapit.NameType')),
            ],
            options={
                'unique_together': {('area', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=500)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='mapit.Area')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='mapit.CodeType')),
            ],
            options={
                'unique_together': {('area', 'type')},
            },
        ),
    ]
